(ns even-fibonnaci-numbers)
(use 'clojure.test)

; Project Euler
;
; Even Fibonnaci Numbers
;
; Problem 2
;
; Each new term in the Fibonacci sequence is generated by adding the previous
; two terms. By starting with 1 and 2, the first 10 terms will be:
;
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
; By considering the terms in the Fibonacci sequence whose values do not exceed
; four million, find the sum of the even-valued terms.;
;
; Solution by twcrone

(def four-mil (* 4 1000000))

(defn fib [i j sum]
  (if (< j four-mil)
    (fib j (+ i j) (if (even? j) (+ sum j) sum))
    sum))

(println (fib 1 2 0))
